color: yellow
fieldLayouts:
  17420966-4f89-45ad-b1a2-7bed3159ceed:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T08:58:20+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6f176841-976d-40f1-b422-6cf8b8b8f7ae
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T09:00:33+00:00'
            elementCondition: null
            fieldUid: e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8 # Plain Text
            handle: subtext
            includeInCards: false
            instructions: null
            label: Subtext
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5099b22-f785-48c0-b000-e1cbf05a7358
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T09:00:33+00:00'
            elementCondition: null
            fieldUid: 35c35080-108d-485f-925f-407a5ab65a22 # Cover
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32fe1fd5-70b3-4b5f-ae5a-d2333038238b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4c1f7531-340c-4e29-b834-24121e40ad0d
        userCondition: null
handle: categories
hasTitleField: true
icon: align-justify
name: Categories
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
