dateModified: 1732271062
email:
  fromEmail: voornaam.naam@howest.be
  fromName: 'Craft Template'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  local:
    hasUrls: true
    name: Local
    settings:
      path: '@webroot/local'
    type: craft\fs\Local
    url: '@web/local'
meta:
  __names__:
    1fd10433-5753-40ec-a11e-340c36af5196: Categories # Categories
    5d45f9f4-7ab7-4459-926d-a8006cad4227: Images # Images
    10d2260b-dd05-4a49-abb3-800017e15928: 'Craft Template' # Craft Template
    21d6f9ae-1d22-490e-bd89-d6ded5d514ac: 'body text' # body text
    28f77b52-1bea-4815-a9c2-0e0e91893a2f: Locations # Locations
    35c35080-108d-485f-925f-407a5ab65a22: Cover # Cover
    41d363ae-4d63-44f1-8dd3-5aac38868e55: Locations # Locations
    78beeaa5-5ed2-4278-8645-1a63a43db403: Carousel # Carousel
    955b3b78-0dbd-47ac-9db5-c15151bf0b94: Details # Details
    1094b8b3-5e0b-4264-b997-5e1e4110a127: House # House
    5071e487-1b49-4d04-8165-7575dfc841f7: City # City
    19178fcc-602e-4e2e-a2a4-abf44f2ec6a3: House # House
    1765228e-0ad3-49c0-a7df-f552ada1e942: State # State
    7968383b-3802-48ad-ac26-58946ebef83b: Categories # Categories
    a3917b41-5b9e-455d-82b1-9867d010e228: 'Body Text' # Body Text
    ace5ebb5-c2db-429c-8968-af0f95b5dc23: 'List Item' # List Item
    bfc5caff-33ac-495a-8336-7abe2887b021: 'Public Schema' # Public Schema
    d3b42bd7-e7fb-4536-8773-1f5957362b49: Price # Price
    e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8: 'Plain Text' # Plain Text
    f6eaef1f-2f88-4856-8eee-c5ae9620f572: 'Craft Template' # Craft Template
    f7593f09-bcc5-495f-a069-b732ce11b5e3: ' Category' #  Category
    fec794db-f77e-45f4-80ea-484e3c502bbf: Strengths # Strengths
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  mapbox:
    edition: standard
    enabled: true
    licenseKey: 3N0Y4A668NC0HQEZ810DC25X
    schemaVersion: 1.1.0
    settings:
      accessToken: null
      enableJsLogging: true
      minifyJsFiles: false
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Craft Template'
  schemaVersion: 5.5.0.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
